#title in header
title: "Thinking Lab"

#main info
#owner
owner: "Marat (Yen-chih, Chen)"
email: yenzhi@gmail.com
info: "A engineer, passionate about fundamental stuff"
#description
desc: ""

#menu
menu:
  Techs: /Techs
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Sydney
placelink: https://goo.gl/maps/73UeKqxJhaxgSseh8
github: https://github.com/maratyz
linkedin: https://www.linkedin.com/in/maratyz/
twitter: https://twitter.com/yenzhit

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: null
